Repository shubhajeet1207/Hackfest-22, pull requests merged in 2022-10, with the labels that each got.

#1 Added segment tree in c
  dsa/Segment Tree in C
Labels: documentation, enhancement, help wanted, hacktoberfest-accepted

#9 name added in contributor.js ✔
  contributors.js
Labels: hacktoberfest, hacktoberfest-accepted

#10 profile added in CONTRIBUTOR.md file �
  CONTRIBUTORS.md
Labels: hacktoberfest, hacktoberfest-accepted

#24 Added carousel
  web/carousel/image1.jpg
  web/carousel/image2.jpg
  web/carousel/image3.jpg
  web/carousel/index.css
  web/carousel/index.html
  web/carousel/index.js
Labels: hacktoberfest, hacktoberfest-accepted

#37 Text-Editor added 👨🏻‍💻
  python_gui/text-editor/.idea/.gitignore
  python_gui/text-editor/.idea/dbnavigator.xml
  python_gui/text-editor/.idea/inspectionProfiles/Project_Default.xml
  python_gui/text-editor/.idea/inspectionProfiles/profiles_settings.xml
  python_gui/text-editor/.idea/misc.xml
  python_gui/text-editor/.idea/modules.xml
  python_gui/text-editor/.idea/typing-test.iml
  python_gui/text-editor/.idea/vcs.xml
  python_gui/text-editor/gui.py
Labels: pending
